from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.uix.label import Label
from android.permissions import request_permissions, Permission
from android import mActivity
from jnius import autoclass

class AssistantUI(BoxLayout):
    def __init__(self, **kwargs):
        super().__init__(orientation='vertical', **kwargs)
        
        # Request microphone and background service permissions on startup
        request_permissions([
            Permission.RECORD_AUDIO,
            Permission.FOREGROUND_SERVICE,
            Permission.POST_NOTIFICATIONS
        ])

        self.status_label = Label(text="Service Stopped")
        self.add_widget(self.status_label)

        self.start_btn = Button(text="Start Voice Assistant")
        self.start_btn.bind(on_release=self.start_service)
        self.add_widget(self.start_btn)

    def start_service(self, instance):
        # Service class generated by Buildozer (org.domain.packagename.ServiceServicename)
        service_name = "org.localai.voiceassistant.ServiceVoiceassistantservice"
        
        service = autoclass(service_name)
        service.start(mActivity, "")
        self.status_label.text = "Service Running in Background"

class MainApp(App):
    def build(self):
        return AssistantUI()

if __name__ == '__main__':
    MainApp().run()

